# SPDX-License-Identifier:	GPL-2.0

obj-$(CONFIG_MMC_WRITE) += make_ext4fs.o \
			ext4_utils.o \
			allocate.o \
			contents.o \
			extent.o \
			indirect.o \
			crc16.o \
			sha1.o \
			libsparse/output_file.o \
			libsparse/backed_block.o \
			libsparse/sparse.o
