obj-y					+= pinctrl-synaptics-core.o

obj-$(CONFIG_PINCTRL_SYNAPTICS_AS370)	+= pinctrl-synaptics-as370.o
obj-$(CONFIG_PINCTRL_SYNAPTICS_VS680)	+= pinctrl-synaptics-vs680.o
obj-$(CONFIG_PINCTRL_SYNAPTICS_VS640)	+= pinctrl-synaptics-vs640.o
