// SPDX-License-Identifier: GPL-2.0+
/*
 * Synaptics pinctrl driver
 *
 * Copyright (C) 2019 Synaptics Corporation
 */

#include <dm/device.h>
#include <dm/pinctrl.h>

#include "pinctrl-synaptics.h"

static const struct synaptics_desc_group as370_soc_pinctrl_groups[] = {
	SYNAPTICS_PINCTRL_GROUP("I2S1_BCLKIO", 0x0, 0x3, 0x00,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO0 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s1"), /* I2S1_BCLKIO */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG0 */
	SYNAPTICS_PINCTRL_GROUP("I2S1_LRCKIO", 0x0, 0x3, 0x03,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO1 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s1"), /* I2S1_LRCKIO */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG1 */
	SYNAPTICS_PINCTRL_GROUP("I2S1_DO0", 0x0, 0x3, 0x06,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "por"), /* POR_1P8V */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s1"), /* I2S1_DO0 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "gpio"), /* GPIO2 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG2 */
	SYNAPTICS_PINCTRL_GROUP("I2S1_DO1", 0x0, 0x3, 0x09,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "por"), /* POR_3P3V */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s1"), /* I2S1_DO1 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "gpio"), /* GPIO3 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG3 */
	SYNAPTICS_PINCTRL_GROUP("I2S1_DO2", 0x0, 0x3, 0x0c,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "por"), /* POR_CORE */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s1"), /* I2S1_DO2 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm4"), /* PWM4 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "gpio"), /* GPIO4 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG4 */
	SYNAPTICS_PINCTRL_GROUP("I2S1_DO3", 0x0, 0x3, 0x0f,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO5 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s1"), /* I2S1_DO3 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm5"), /* PWM5 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "spdifib"), /* SPDIFIB */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "spdifo"), /* SPDIFO */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG5 */
	SYNAPTICS_PINCTRL_GROUP("I2S1_MCLK", 0x0, 0x3, 0x12,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO6 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s1"), /* I2S1_MCLK */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG6 */
	SYNAPTICS_PINCTRL_GROUP("I2S2_BCLKIO", 0x0, 0x3, 0x15,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO7 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s2"), /* I2S2_BCLKIO */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG7 */
	SYNAPTICS_PINCTRL_GROUP("I2S2_LRCKIO", 0x0, 0x3, 0x18,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO8 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s2"), /* I2S2_LRCKIO */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG8 */
	SYNAPTICS_PINCTRL_GROUP("I2S2_DI0", 0x0, 0x3, 0x1b,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO9 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s2"), /* I2S2_DI0 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm2"), /* PWM2 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG9 */
	SYNAPTICS_PINCTRL_GROUP("I2S2_DI1", 0x4, 0x3, 0x00,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO10 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s2"), /* I2S2_DI1 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm3"), /* PWM3 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG10 */
	SYNAPTICS_PINCTRL_GROUP("I2S2_DI2", 0x4, 0x3, 0x03,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO11 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s2"), /* I2S2_DI2 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm6"), /* PWM6 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG11 */
	SYNAPTICS_PINCTRL_GROUP("I2S2_DI3", 0x4, 0x3, 0x06,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO12 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s2"), /* I2S2_DI3 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm7"), /* PWM7 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "spdifia"), /* SPDIFIA */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "spdifo"), /* SPDIFO */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG12 */
	SYNAPTICS_PINCTRL_GROUP("PDM_CLKO", 0x4, 0x3, 0x09,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO13 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pdm"), /* PDM_CLKO */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "i2s2"), /* I2S2_MCLK */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG13 */
	SYNAPTICS_PINCTRL_GROUP("PDM_DI0", 0x4, 0x3, 0x0c,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO14 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pdm"), /* PDM_DI0 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG14 */
	SYNAPTICS_PINCTRL_GROUP("PDM_DI1", 0x4, 0x3, 0x0f,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO15 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pdm"), /* PDM_DI1 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG15 */
	SYNAPTICS_PINCTRL_GROUP("PDM_DI2", 0x4, 0x3, 0x12,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO16 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pdm"), /* PDM_DI2 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm4"), /* PWM4 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG16 */
	SYNAPTICS_PINCTRL_GROUP("PDM_DI3", 0x4, 0x3, 0x15,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO17 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pdm"), /* PDM_DI3 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm5"), /* PWM5 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "spdifi"), /* SPDIFI */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "spdifo"), /* SPDIFO */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG17 */
	SYNAPTICS_PINCTRL_GROUP("NAND_IO0", 0x4, 0x3, 0x18,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_IO0 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "emmc"), /* EMMC_DATA0 */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "pcie0")), /* PCIE0_MDIO */
	SYNAPTICS_PINCTRL_GROUP("NAND_IO1", 0x4, 0x3, 0x1b,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_IO1 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "emmc"), /* EMMC_DATA1 */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "pcie0")), /* PCIE0_MDC */
	SYNAPTICS_PINCTRL_GROUP("NAND_IO2", 0x8, 0x3, 0x00,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_IO2 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "emmc"), /* EMMC_DATA2 */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "pcie1")), /* PCIE1_MDIO */
	SYNAPTICS_PINCTRL_GROUP("NAND_IO3", 0x8, 0x3, 0x03,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_IO3 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "emmc"), /* EMMC_DATA3 */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "pcie1")), /* PCIE1_MDC */
	SYNAPTICS_PINCTRL_GROUP("NAND_IO4", 0x8, 0x3, 0x06,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_IO4 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "emmc")), /* EMMC_DATA4 */
	SYNAPTICS_PINCTRL_GROUP("NAND_IO5", 0x8, 0x3, 0x09,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_IO5 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "emmc")), /* EMMC_DATA5 */
	SYNAPTICS_PINCTRL_GROUP("NAND_IO6", 0x8, 0x3, 0x0c,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* NAND_IO6 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "emmc")), /* EMMC_DATA6 */
	SYNAPTICS_PINCTRL_GROUP("NAND_IO7", 0x8, 0x3, 0x0f,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* NAND_IO7 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "emmc")), /* EMMC_DATA7 */
	SYNAPTICS_PINCTRL_GROUP("NAND_ALE", 0x8, 0x3, 0x12,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_ALE */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm6"), /* PWM6 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "gpio")), /* GPIO18 */
	SYNAPTICS_PINCTRL_GROUP("NAND_CLE", 0x8, 0x3, 0x15,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_CLE */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm7"), /* PWM7 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "gpio")), /* GPIO19 */
	SYNAPTICS_PINCTRL_GROUP("NAND_WEn", 0x8, 0x3, 0x18,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_WEn */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "gpio")), /* GPIO20 */
	SYNAPTICS_PINCTRL_GROUP("NAND_REn", 0x8, 0x3, 0x1b,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_REn */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "gpio")), /* GPIO21 */
	SYNAPTICS_PINCTRL_GROUP("NAND_WPn", 0xc, 0x3, 0x00,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_WPn */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "emmc"), /* EMMC_CLK */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "gpio")), /* GPIO22 */
	SYNAPTICS_PINCTRL_GROUP("NAND_CEn", 0xc, 0x3, 0x03,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_CEn */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "emmc"), /* EMMC_RSTn */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "gpio")), /* GPIO23 */
	SYNAPTICS_PINCTRL_GROUP("NAND_RDY", 0xc, 0x3, 0x06,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "nand"), /* NAND_RDY */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "emmc"), /* EMMC_CMD */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "gpio")), /* GPIO24 */
	SYNAPTICS_PINCTRL_GROUP("SPI1_SS0n", 0xc, 0x3, 0x09,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "spi1"), /* SPI1_SS0n */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "gpio")), /* GPIO25 */
	SYNAPTICS_PINCTRL_GROUP("SPI1_SS1n", 0xc, 0x3, 0x0c,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "spi1"), /* SPI1_SS1n */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "gpio"), /* GPIO26 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "pwm2")), /* PWM2 */
	SYNAPTICS_PINCTRL_GROUP("SPI1_SS2n", 0xc, 0x3, 0x0f,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "uart0"), /* URT0_RXD */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "spi1"), /* SPI1_SS2n */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "gpio"), /* GPIO27 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "pwm3")), /* PWM3 */
	SYNAPTICS_PINCTRL_GROUP("SPI1_SS3n", 0xc, 0x3, 0x12,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "uart0"), /* URT0_TXD */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "spi1"), /* SPI1_SS3n */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "gpio")), /* GPIO28 */
	SYNAPTICS_PINCTRL_GROUP("SPI1_SCLK", 0xc, 0x3, 0x15,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "spi1"), /* SPI1_SCLK */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO29 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "pwm4")), /* PWM4 */
	SYNAPTICS_PINCTRL_GROUP("SPI1_SDO", 0xc, 0x3, 0x18,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "spi1"), /* SPI1_SDO */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO30 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "pwm5")), /* PWM5 */
	SYNAPTICS_PINCTRL_GROUP("SPI1_SDI", 0xc, 0x3, 0x1b,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "spi1"), /* SPI1_SDI */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "gpio")), /* GPIO31 */
	SYNAPTICS_PINCTRL_GROUP("USB0_DRV_VBUS", 0x10, 0x3, 0x00,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "usb0"), /* USB0_DRV_VBUS */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO32 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "refclk"), /* REFCLKO_25M */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "pwm1")), /* PWM1 */
	SYNAPTICS_PINCTRL_GROUP("TW1_SCL", 0x10, 0x3, 0x03,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO33 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "tw1")), /* TW1_SCL */
	SYNAPTICS_PINCTRL_GROUP("TW1_SDA", 0x10, 0x3, 0x06,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO34 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "tw1")), /* TW1_SDA */
	SYNAPTICS_PINCTRL_GROUP("TW0_SCL", 0x10, 0x3, 0x09,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO35 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "tw0")), /* TW0_SCL */
	SYNAPTICS_PINCTRL_GROUP("TW0_SDA", 0x10, 0x3, 0x0c,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO36 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "tw0")), /* TW0_SDA */
	SYNAPTICS_PINCTRL_GROUP("TMS", 0x10, 0x3, 0x0f,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "jtag"), /* TMS */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO37 */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "pwm0")), /* PWM0 */
	SYNAPTICS_PINCTRL_GROUP("TDI", 0x10, 0x3, 0x12,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "jtag"), /* TDI */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO38 */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "pwm1")), /* PWM1 */
	SYNAPTICS_PINCTRL_GROUP("TDO", 0x10, 0x3, 0x15,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "jtag"), /* TDO */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO39 */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "pwm0")), /* PWM0 */
	SYNAPTICS_PINCTRL_GROUP("PWM6", 0x10, 0x3, 0x18,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO40 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pwm6")), /* PWM6 */
	SYNAPTICS_PINCTRL_GROUP("PWM7", 0x10, 0x3, 0x1b,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO41 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pwm7")), /* PWM7 */
	SYNAPTICS_PINCTRL_GROUP("PWM0", 0x14, 0x3, 0x00,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "por"), /* POR_VDDCPUSOC */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pwm0"), /* PWM0 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "gpio")), /* GPIO42 */
	SYNAPTICS_PINCTRL_GROUP("PWM1", 0x14, 0x3, 0x03,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO43 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pwm1")), /* PWM1 */
	SYNAPTICS_PINCTRL_GROUP("PWM2", 0x14, 0x3, 0x06,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO44 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pwm2")), /* PWM2 */
	SYNAPTICS_PINCTRL_GROUP("PWM3", 0x14, 0x3, 0x09,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO45 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pwm3")), /* PWM3 */
	SYNAPTICS_PINCTRL_GROUP("PWM4", 0x14, 0x3, 0x0c,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO46 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pwm4")), /* PWM4 */
	SYNAPTICS_PINCTRL_GROUP("PWM5", 0x14, 0x3, 0x0f,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO47 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "pwm5")), /* PWM5 */
	SYNAPTICS_PINCTRL_GROUP("URT1_RTSn", 0x14, 0x3, 0x12,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO48 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "uart1"), /* URT1_RTSn */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm6"), /* PWM6 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "tw1"), /* TW1A_SCL */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "aio"), /* AIO_DBG0 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG18 */
	SYNAPTICS_PINCTRL_GROUP("URT1_CTSn", 0x14, 0x3, 0x15,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO49 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "uart1"), /* URT1_CTSn */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "pwm7"), /* PWM7 */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "tw1"), /* TW1A_SDA */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "aio"), /* AIO_DBG1 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG19 */
	SYNAPTICS_PINCTRL_GROUP("URT1_RXD", 0x14, 0x3, 0x18,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO50 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "uart1"), /* URT1_RXD */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "aio"), /* AIO_DBG2 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG20 */
	SYNAPTICS_PINCTRL_GROUP("URT1_TXD", 0x14, 0x3, 0x1b,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO51 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "uart1"), /* URT1_TXD */
			SYNAPTICS_PINCTRL_FUNCTION(0x4, "aio"), /* AIO_DBG3 */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG21 */
	SYNAPTICS_PINCTRL_GROUP("I2S3_DI", 0x18, 0x3, 0x00,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO52 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s3"), /* I2S3_DI */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG22 */
	SYNAPTICS_PINCTRL_GROUP("I2S3_DO", 0x18, 0x3, 0x03,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO53 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s3"), /* I2S3_DI */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "phy")), /* PHY_DBG23 */
	SYNAPTICS_PINCTRL_GROUP("I2S3_BCLKIO", 0x18, 0x3, 0x06,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO54 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s3"), /* I2S3_BCLKIO */
			SYNAPTICS_PINCTRL_FUNCTION(0x5, "clk")), /* CLK_DBG */
	SYNAPTICS_PINCTRL_GROUP("I2S3_LRCKIO", 0x18, 0x3, 0x09,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO55 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "i2s3")), /* I2S3_LRCKIO */
	SYNAPTICS_PINCTRL_GROUP("SD0_DAT0", 0x18, 0x3, 0x0c,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "clk"), /* CPUPLL_OUT */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "sd0"), /* SD0_DAT0 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "gpio")), /* GPIO56 */
	SYNAPTICS_PINCTRL_GROUP("SD0_DAT1", 0x18, 0x3, 0x0f,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "clk"), /* SYSPLL_OUT */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "sd0"), /* SD0_DAT1 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "gpio")), /* GPIO57 */
	SYNAPTICS_PINCTRL_GROUP("SD0_CLK", 0x18, 0x3, 0x12,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO58 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "sd0")), /* SD0_CLK */
	SYNAPTICS_PINCTRL_GROUP("SD0_DAT2", 0x18, 0x3, 0x15,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "clk"), /* MEMPLL_OUT */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "sd0"), /* SD0_DAT2 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "gpio")), /* GPIO59 */
	SYNAPTICS_PINCTRL_GROUP("SD0_DAT3", 0x18, 0x3, 0x18,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "clk"), /* APLL0_OUT */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "sd0"), /* SD0_DAT3 */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "gpio")), /* GPIO60 */
	SYNAPTICS_PINCTRL_GROUP("SD0_CMD", 0x18, 0x3, 0x1b,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "clk"), /* APLL1_OUT */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "sd0"), /* SD0_CMD */
			SYNAPTICS_PINCTRL_FUNCTION(0x2, "gpio")), /* GPIO61 */
	SYNAPTICS_PINCTRL_GROUP("SD0_CDn", 0x1c, 0x3, 0x00,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO62 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "sd0"), /* SD0_CDn */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "pwm2")), /* PWM2 */
	SYNAPTICS_PINCTRL_GROUP("SD0_WP", 0x1c, 0x3, 0x03,
			SYNAPTICS_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO63 */
			SYNAPTICS_PINCTRL_FUNCTION(0x1, "sd0"), /* SD0_WP */
			SYNAPTICS_PINCTRL_FUNCTION(0x3, "pwm3")), /* PWM3 */
};

static int as370_pinctrl_probe(struct udevice *dev)
{
	const struct synaptics_pinctrl_desc *desc = (struct synaptics_pinctrl_desc *)dev_get_driver_data(dev);
	return synaptics_pinctrl_probe(dev, desc);
}

static const struct synaptics_pinctrl_desc as370_soc_pinctrl_data = {
	.groups = as370_soc_pinctrl_groups,
	.ngroups = ARRAY_SIZE(as370_soc_pinctrl_groups),
};


static const struct udevice_id as370_pinctrl_match[] = {
	{
		.compatible = "syna,as370-soc-pinctrl",
		.data = (ulong)&as370_soc_pinctrl_data,
	},
	{}
};

U_BOOT_DRIVER(as370_pinctrl) = {
	.name		= "as370-pinctrl",
	.id		= UCLASS_PINCTRL,
	.of_match	= as370_pinctrl_match,
	.ops		= &synaptics_pinctrl_ops,
	.probe		= as370_pinctrl_probe,
	.priv_auto_alloc_size = sizeof(struct synaptics_pinctrl),
};
