# SPDX-License-Identifier: GPL-2.0

ifdef CONFIG_VIDEO_SPACEMIT
obj-y += dsi/
obj-y += spacemit_dpu.o
obj-$(CONFIG_DISPLAY_SPACEMIT_MIPI) += spacemit_mipi.o
obj-$(CONFIG_DISPLAY_SPACEMIT_HDMI) += spacemit_hdmi.o

endif
