#
# board/renesas/bananapi-ai2n/Makefile
#
# Copyright (C) 2023 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	:= ../rcar-common/gen3-spl.o
else
obj-y	:= bananapi-ai2n.o ../rcar-common/common.o board-info.o
endif
