# SPDX-License-Identifier: GPL-2.0

obj-y += video/spacemit_video_tx.o \
		video/spacemit_mipi_port.o \
		drv/spacemit_dphy.o \
		drv/spacemit_dsi_common.o \
		drv/spacemit_dsi_drv.o

obj-y += video/lcd/lcd_icnl9911c.o
obj-y += video/lcd/lcd_gx09inx101.o

