# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_SYNA_USB_PHY) += usb_phy_syna.o
obj-$(CONFIG_TARGET_VS680) += usb_phy_vs680.o
obj-$(CONFIG_TARGET_VS680_A0) += usb_phy_vs680.o
obj-$(CONFIG_TARGET_VS640) += usb_phy_vs680.o
