# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_SYNA_GEN2_FLOW) += usbload.o
obj-$(CONFIG_SYNA_GENX_FLOW) += usbload_genx.o
obj-$(CONFIG_ARCH_SYNAPTICS) += imageload.o
obj-$(CONFIG_ARCH_SYNAPTICS) += runscript.o
obj-$(CONFIG_MMC_WRITE) += emmcburn.o
obj-$(CONFIG_CMD_SYNA_NAND) += hpnfc_nand.o syna_nand.o
obj-$(CONFIG_CMD_SYNA_FASTBOOT_GUI) += fastboot_gui.o
obj-$(CONFIG_CMD_SYNA_FTS) += flash_ts.o
obj-$(CONFIG_CMD_SYNA_PRELOAD_TA) += preload_ta.o