# SPDX-License-Identifier: GPL-2.0-or-later
#
# Phy supports for Spacemit k1x SoCs
#

obj-$(CONFIG_$(SPL_)PHY_SPACEMIT_K1X_USB2)	+= k1x-usb2-ci-phy.o
obj-$(CONFIG_$(SPL_)PHY_SPACEMIT_K1X_COMBPHY)	+= k1x-combphy.o
