/* SPDX-License-Identifier: GPL-2.0+ */

#ifndef __DT_BINDINGS_POWER_DOMAIN_K1X_H
#define __DT_BINDINGS_POWER_DOMAIN_K1X_H

#define K1X_PMU_VPU_PWR_DOMAIN  0
#define K1X_PMU_GPU_PWR_DOMAIN  1
#define K1X_PMU_LCD_PWR_DOMAIN  2
#define K1X_PMU_ISP_PWR_DOMAIN  3
#define K1X_PMU_AUD_PWR_DOMAIN  4
#define K1X_PMU_GNSS_PWR_DOMAIN 5
#define K1X_PMU_HDMI_PWR_DOMAIN 6

#endif /* __DT_BINDINGS_POWER_DOMAIN_K1X_H */
